---
name: "Lint & Test"
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "!dependabot/*"
      - "main"
  pull_request:
    branches: ["*"]
jobs:
  go-lint:
    name: "Lint Go"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "authzed/actions/setup-go@main"
      - uses: "authzed/actions/gofumpt@main"
      - uses: "authzed/actions/go-mod-tidy@main"
      - uses: "authzed/actions/go-mod-tidy@main"
        with:
          working_directory: "e2e"
      - uses: "authzed/actions/golangci-lint@main"
      - uses: "authzed/actions/golangci-lint@main"
        with:
          working_directory: "e2e"
      - uses: "authzed/actions/govulncheck@main"
  test:
    name: "Run Unit Tests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "authzed/actions/setup-go@main"
      - uses: "authzed/actions/go-test@main"
  e2e:
    name: "Run E2E Fault Injection Tests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "authzed/actions/setup-go@main"
      - uses: "authzed/actions/go-test@main"
        with:
          working_directory: "e2e"
          timeout: "10m"
        env:
          E2E_RESULTS_DIR: "${{ runner.temp }}/e2e-results"
      - uses: "actions/upload-artifact@v4"
        if: "always()"
        with:
          name: "e2e-results"
          path: "${{ runner.temp }}/e2e-results"
  codeql:
    name: "Analyze with CodeQL"
    runs-on: "ubuntu-latest"
    permissions:
      actions: "read"
      contents: "read"
      security-events: "write"
    strategy:
      fail-fast: false
      matrix:
        language: ["go"]
    steps:
      - uses: "actions/checkout@v3"
      - uses: "authzed/actions/codeql@main"
